# H2
server.port: 7999

# Spring
spring:
  datasource:
    url: "jdbc:h2:mem:testdb"
    driver-class-name: "org.h2.Driver"
    username: "sa"
    password: "password"
  h2:
    console:
      enabled: true
  profiles:
    active: loadInitialData
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 587
    username: username
    password: password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true